#!/bin/bash

errors=0

DC_EXCLUSIONS='mptr|method\('

echo test openmethods...

if ! dub test -q openmethods $*;
then
    echo "ERROR"
    errors=1
fi

for dir in tests examples
do
    echo "$dir..."

    for target in $(ls $dir)
    do
        if [ -d $dir/$target ];
        then
            echo $target
            if [[ "$DC" == 'gdc' ]] && grep --quiet -P $DC_EXCLUSIONS `find $dir/$target -name '*.d'`;
            then
                echo SKIP $target
            else

                if ! dub test -q openmethods:$target $*;
                then
                    echo "ERROR"
                    errors=1
                fi

                if ! grep --quiet library $dir/$target/dub.sdl;
                then
                    if ! dub run -q openmethods:$target $*;
                    then
                        echo "ERROR"
                        errors=1
                    fi
                fi
            fi
        fi

        if [[ $target == *'.d' ]]
        then
            echo $target

            if [[ "$DC" == 'gdc' ]] && grep --quiet -P $DC_EXCLUSIONS $dir/$target;
            then
                echo SKIP $target
                continue
            fi

            if ! dub run --single -q $dir/$target $*;
            then
                echo "ERROR"
                errors=1
            fi
        fi


        # if [[ "$DC" == 'gdc' ]] && grep --quiet -P $DC_EXCLUSIONS `find examples/$target -name '*.d'`;
        # then
        #     echo SKIP $target
        #     continue
        # fi

        # echo test $target...

        # if ! dub test -q openmethods:$target $*;
        # then
        #     echo "ERROR"
        #     errors=1
        # fi

        # echo run $target...

        # if ! dub run -q openmethods:$target $*;
        # then
        #     echo "ERROR"
        #     errors=1
        # fi
    done
done

if [ $errors -ne 0 ]
then
   echo "ERRORS!"
   exit 1
fi
